version: '3.7'
services:
  app:
    image: dock.pfdev.de/plusforta/${projectName}-${appName}:${tagName}
    networks:
      - web
    entrypoint: /usr/local/bin/docker-php-entrypoint
    command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    secrets:
      - source: dotEnv
        target: /var/www/app/.env
        uid: '33'
        gid: '33'
        mode: 0440
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.aak.rule=Host(`${host1}`) || Host(`${host2}`)
        - "traefik.http.services.aak.loadbalancer.server.port=80"
        - traefik.http.routers.aak.entrypoints=websecure
        - traefik.http.routers.aak.tls.certresolver=default
        - "traefik.http.routers.aak.tls.options=intermediate@file"
        - "traefik.http.routers.aak.middlewares=hstsHeaders@file"

networks:
  web: # defines the network used to connect to traefik in another container
    external:
      name: web
secrets:
  dotEnv:
    file: ./.env
    name: dotEnv-${envHash}
